#page title
page_title                                : MDT                                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

initials                                  : MDT
app_icon                                  : assets/logo.png                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
name                                      : Mayra Diaz Tramontana                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
type                                      : Senior Computer Science                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
description                               : See all my projects, experience, skills and other relevant information.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Mayra Diaz Tramontana                               
your_link                                 : https://www.linkedin.com/in/mayra-dt/                     
your_city                                 : Lima                                
email_address                             : mayra.diaz.tramontana@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
linkedin_username                         : mayra-dt
github_username                           : mayra-diaz
youtube_username                          :


# About me
long_description                          : Senior student of Computer Science at the University of Engineering and Technology UTEC. Currently at the Colorado School of Mines for an exchange program. I have extensive experience in project management, agile methodologies, database design and implementation, predictive and machine learning models and complex data structures. I enjoy volunteering, such as supporting student organizations. I hope to contribute to the world in whatever role I play. I am interested in technology innovation projects and digital transformation. My academic interests include cryptography and data analytics. I am seeking to participate in research projects and challenging internships.

# Skills list
skills                                    :
  - title                                 : Computer Science
    description                           : "Object oriented programming, database design and implementation, machine learning, data visualization, research skills, advanced data structures, agile methodologies: SCRUM, Design Thinking, Kanban."
    fontawesome_icon_name                 : brain
    special                               : true

  - title                                 : Libraries and frameworks
    description                           : ROS, Scikit-learn, Matplotlib, Pandas, GameMaker, Unity, Django, React, Springboot, Latex.
    fontawesome_icon_name                 : cube
    special                               : false
  
  - title                                 : Languages
    description                           : Written and verbal fluency in English and Spanish, basic Portuguese.
    fontawesome_icon_name                 : globe
    special                               : false

  - title                                 : Advanced programming 
    description                           : C/C++, Python, Javascript, Typescript, Java, R, MATLAB, Scilab, SQL, Tableau, CSS.
    fontawesome_icon_name                 : code
    special                               : false

  - title                                 : Soft skills
    description                           : Leadership, teamwork, adaptability, organization, problem solving, time management, scheduling, critical thinking.
    fontawesome_icon_name                 : handshake
    special                               : false

    
# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : GitHub Pages Jekyll Theme
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
    fontawesome_icon_name                 : magic
    
  - title                                 : iPhone Device Preview
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : mobile

  - title                                 : Video Support
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : play-circle

  - title                                 : Automatic Icon and Metadata
    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    fontawesome_icon_name                 : sync

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : star

  - title                                 : Smart App Banner
    description                           : Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Social Links
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : link

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/background_stars.avif                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#47303d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#F558B1"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#F558B1"
feature_icons_background_color            : "#F2D1E2"

social_icons_foreground_color             : "#F558B1"
social_icons_background_color             : "#F2D1E2"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
